.TH "accountwidget.cpp" 3 "VEDA-Qt-BANK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
accountwidget.cpp
.SH SYNOPSIS
.br
.PP
\fR#include 'accountwidget\&.h'\fP
.br
\fR#include <QHBoxLayout>\fP
.br
\fR#include <QVBoxLayout>\fP
.br
\fR#include <QSpacerItem>\fP
.br
\fR#include <QLocale>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for VEDA-Qt-BANK from the source code\&.
