.TH "VEDA-Qt-BANK/addaccountdialog.h" 3 "VEDA-Qt-BANK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VEDA-Qt-BANK/addaccountdialog.h
.SH SYNOPSIS
.br
.PP
\fR#include <QDialog>\fP
.br
\fR#include <QLineEdit>\fP
.br
\fR#include <QPushButton>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAddAccountDialog\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for VEDA-Qt-BANK from the source code\&.
