.TH "bankmodel.h" 3 "VEDA-Qt-BANK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bankmodel.h
.SH SYNOPSIS
.br
.PP
\fR#include <QObject>\fP
.br
\fR#include <QString>\fP
.br
\fR#include <QList>\fP
.br
\fR#include <QVariant>\fP
.br
\fR#include <QMap>\fP
.br
\fR#include <QSqlDatabase>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAccount\fP"
.br
.ti -1c
.RI "class \fBTransaction\fP"
.br
.ti -1c
.RI "class \fBBankModel\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for VEDA-Qt-BANK from the source code\&.
