.TH "VEDA-Qt-BANK/checkanimationwidget.h" 3 "VEDA-Qt-BANK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VEDA-Qt-BANK/checkanimationwidget.h
.SH SYNOPSIS
.br
.PP
\fR#include <QWidget>\fP
.br
\fR#include <QPropertyAnimation>\fP
.br
\fR#include <QTimer>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCheckAnimationWidget\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for VEDA-Qt-BANK from the source code\&.
