.TH "checkanimationwidget.cpp" 3 "VEDA-Qt-BANK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
checkanimationwidget.cpp
.SH SYNOPSIS
.br
.PP
\fR#include 'checkanimationwidget\&.h'\fP
.br
\fR#include <QPainter>\fP
.br
\fR#include <QPainterPath>\fP
.br
\fR#include <QDebug>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for VEDA-Qt-BANK from the source code\&.
