.TH "completionwidget.cpp" 3 "VEDA-Qt-BANK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
completionwidget.cpp
.SH SYNOPSIS
.br
.PP
\fR#include 'completionwidget\&.h'\fP
.br
\fR#include 'checkanimationwidget\&.h'\fP
.br
\fR#include <QVBoxLayout>\fP
.br
\fR#include <QHBoxLayout>\fP
.br
\fR#include <QLocale>\fP
.br
\fR#include <QStyle>\fP
.br
\fR#include <QTimer>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for VEDA-Qt-BANK from the source code\&.
