.TH "VEDA-Qt-BANK/dashboardwidget.cpp" 3 "VEDA-Qt-BANK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VEDA-Qt-BANK/dashboardwidget.cpp
.SH SYNOPSIS
.br
.PP
\fR#include 'dashboardwidget\&.h'\fP
.br
\fR#include 'addaccountdialog\&.h'\fP
.br
\fR#include <QMouseEvent>\fP
.br
\fR#include <QHBoxLayout>\fP
.br
\fR#include <QVBoxLayout>\fP
.br
\fR#include <QSpacerItem>\fP
.br
\fR#include <QLocale>\fP
.br
\fR#include <QMessageBox>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for VEDA-Qt-BANK from the source code\&.
