.TH "VEDA-Qt-BANK/dashboardwidget.h" 3 "VEDA-Qt-BANK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VEDA-Qt-BANK/dashboardwidget.h
.SH SYNOPSIS
.br
.PP
\fR#include <QWidget>\fP
.br
\fR#include <QLabel>\fP
.br
\fR#include <QPushButton>\fP
.br
\fR#include <QListWidget>\fP
.br
\fR#include <QVBoxLayout>\fP
.br
\fR#include <QDialog>\fP
.br
\fR#include 'bankmodel\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAccountListItem\fP"
.br
.ti -1c
.RI "class \fBDashboardWidget\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for VEDA-Qt-BANK from the source code\&.
