.TH "LoginWidget" 3 "VEDA-Qt-BANK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LoginWidget
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <loginwidget\&.h>\fP
.PP
Inherits QWidget\&.
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBloginRequested\fP (const QString &username, const QString &password)"
.br
.ti -1c
.RI "void \fBregisterRequested\fP ()"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLoginWidget\fP (QWidget *parent=nullptr)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "LoginWidget::LoginWidget (QWidget * parent = \fRnullptr\fP)\fR [explicit]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void LoginWidget::loginRequested (const QString & username, const QString & password)\fR [signal]\fP"

.SS "void LoginWidget::registerRequested ()\fR [signal]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for VEDA-Qt-BANK from the source code\&.
