.TH "MainWindow" 3 "VEDA-Qt-BANK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MainWindow
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <mainwindow\&.h>\fP
.PP
Inherits QMainWindow\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMainWindow\fP (QWidget *parent=nullptr)"
.br
.ti -1c
.RI "\fB~MainWindow\fP ()"
.br
.ti -1c
.RI "void \fBshowLoginScreen\fP ()"
.br
.ti -1c
.RI "void \fBshowDashboardScreen\fP ()"
.br
.ti -1c
.RI "void \fBshowAccountScreen\fP (const QString &accountNumber)"
.br
.ti -1c
.RI "void \fBshowTransactionScreen\fP (const QString &accountNumber, const QString &transactionType)"
.br
.ti -1c
.RI "void \fBshowVerificationScreen\fP ()"
.br
.ti -1c
.RI "void \fBshowCompletionScreen\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MainWindow::MainWindow (QWidget * parent = \fRnullptr\fP)\fR [explicit]\fP"

.SS "MainWindow::~MainWindow ()"

.SH "Member Function Documentation"
.PP 
.SS "void MainWindow::showAccountScreen (const QString & accountNumber)"

.SS "void MainWindow::showCompletionScreen ()"

.SS "void MainWindow::showDashboardScreen ()"

.SS "void MainWindow::showLoginScreen ()"

.SS "void MainWindow::showTransactionScreen (const QString & accountNumber, const QString & transactionType)"

.SS "void MainWindow::showVerificationScreen ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for VEDA-Qt-BANK from the source code\&.
