.TH "mainwindow.h" 3 "VEDA-Qt-BANK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mainwindow.h
.SH SYNOPSIS
.br
.PP
\fR#include <QMainWindow>\fP
.br
\fR#include <QStackedWidget>\fP
.br
\fR#include 'bankmodel\&.h'\fP
.br
\fR#include 'loginwidget\&.h'\fP
.br
\fR#include 'dashboardwidget\&.h'\fP
.br
\fR#include 'accountwidget\&.h'\fP
.br
\fR#include 'transactionwidget\&.h'\fP
.br
\fR#include 'verificationwidget\&.h'\fP
.br
\fR#include 'completionwidget\&.h'\fP
.br
\fR#include 'registerdialog\&.h'\fP
.br
\fR#include <QStack>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMainWindow\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for VEDA-Qt-BANK from the source code\&.
