.TH "registerdialog.cpp" 3 "VEDA-Qt-BANK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
registerdialog.cpp
.SH SYNOPSIS
.br
.PP
\fR#include 'registerdialog\&.h'\fP
.br
\fR#include <QVBoxLayout>\fP
.br
\fR#include <QLabel>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for VEDA-Qt-BANK from the source code\&.
