.TH "TransactionListItem" 3 "VEDA-Qt-BANK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TransactionListItem
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <accountwidget\&.h>\fP
.PP
Inherits QWidget\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTransactionListItem\fP (const QVariantMap &transactionData, QWidget *parent=nullptr)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TransactionListItem::TransactionListItem (const QVariantMap & transactionData, QWidget * parent = \fRnullptr\fP)\fR [explicit]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for VEDA-Qt-BANK from the source code\&.
