.TH "verificationwidget.cpp" 3 "VEDA-Qt-BANK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
verificationwidget.cpp
.SH SYNOPSIS
.br
.PP
\fR#include 'verificationwidget\&.h'\fP
.br
\fR#include <QVBoxLayout>\fP
.br
\fR#include <QHBoxLayout>\fP
.br
\fR#include <QIntValidator>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for VEDA-Qt-BANK from the source code\&.
