.TH "Account" 3 "VEDA-Qt-BANK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Account
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <bankmodel\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAccount\fP (const QString &number, const QString &name, qint64 initialBalance)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "QString \fBaccountNumber\fP"
.br
.ti -1c
.RI "QString \fBaccountName\fP"
.br
.ti -1c
.RI "qint64 \fBbalance\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Account::Account (const QString & number, const QString & name, qint64 initialBalance)\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "QString Account::accountName"

.SS "QString Account::accountNumber"

.SS "qint64 Account::balance"


.SH "Author"
.PP 
Generated automatically by Doxygen for VEDA-Qt-BANK from the source code\&.
