.TH "AddAccountDialog" 3 "VEDA-Qt-BANK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AddAccountDialog
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <addaccountdialog\&.h>\fP
.PP
Inherits QDialog\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAddAccountDialog\fP (QWidget *parent=nullptr)"
.br
.ti -1c
.RI "QString \fBaccountName\fP () const"
.br
.ti -1c
.RI "QString \fBaccountNumber\fP () const"
.br
.ti -1c
.RI "bool \fBisValidAccountNumber\fP (const QString &\fBaccountNumber\fP) const"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AddAccountDialog::AddAccountDialog (QWidget * parent = \fRnullptr\fP)\fR [explicit]\fP"

.SH "Member Function Documentation"
.PP 
.SS "QString AddAccountDialog::accountName () const"

.SS "QString AddAccountDialog::accountNumber () const"

.SS "bool AddAccountDialog::isValidAccountNumber (const QString & accountNumber) const"


.SH "Author"
.PP 
Generated automatically by Doxygen for VEDA-Qt-BANK from the source code\&.
