.TH "bankmodel.cpp" 3 "VEDA-Qt-BANK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bankmodel.cpp
.SH SYNOPSIS
.br
.PP
\fR#include 'bankmodel\&.h'\fP
.br
\fR#include <QDateTime>\fP
.br
\fR#include <QSqlQuery>\fP
.br
\fR#include <QSqlError>\fP
.br
\fR#include <QRandomGenerator>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for VEDA-Qt-BANK from the source code\&.
