.TH "CompletionWidget" 3 "VEDA-Qt-BANK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CompletionWidget
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <completionwidget\&.h>\fP
.PP
Inherits QWidget\&.
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBbackToAccountRequested\fP ()"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCompletionWidget\fP (QWidget *parent=nullptr)"
.br
.ti -1c
.RI "void \fBsetupForTransaction\fP (const QString &transactionType, double amount)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CompletionWidget::CompletionWidget (QWidget * parent = \fRnullptr\fP)\fR [explicit]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void CompletionWidget::backToAccountRequested ()\fR [signal]\fP"

.SS "void CompletionWidget::setupForTransaction (const QString & transactionType, double amount)"


.SH "Author"
.PP 
Generated automatically by Doxygen for VEDA-Qt-BANK from the source code\&.
