.TH "loginwidget.cpp" 3 "VEDA-Qt-BANK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
loginwidget.cpp
.SH SYNOPSIS
.br
.PP
\fR#include 'loginwidget\&.h'\fP
.br
\fR#include <QPixmap>\fP
.br
\fR#include <QHBoxLayout>\fP
.br
\fR#include <QVBoxLayout>\fP
.br
\fR#include <QSpacerItem>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for VEDA-Qt-BANK from the source code\&.
