.TH "QInt64Validator" 3 "VEDA-Qt-BANK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QInt64Validator
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <transactionwidget\&.h>\fP
.PP
Inherits QValidator\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBQInt64Validator\fP (qint64 min, qint64 max, QObject *parent=nullptr)"
.br
.ti -1c
.RI "State \fBvalidate\fP (QString &input, int &pos) const override"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "QInt64Validator::QInt64Validator (qint64 min, qint64 max, QObject * parent = \fRnullptr\fP)\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "State QInt64Validator::validate (QString & input, int & pos) const\fR [inline]\fP, \fR [override]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for VEDA-Qt-BANK from the source code\&.
