.TH "RegisterDialog" 3 "VEDA-Qt-BANK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RegisterDialog
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <registerdialog\&.h>\fP
.PP
Inherits QDialog\&.
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBregisterUser\fP (const QString &username, const QString &password)"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRegisterDialog\fP (QWidget *parent=nullptr)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "RegisterDialog::RegisterDialog (QWidget * parent = \fRnullptr\fP)\fR [explicit]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void RegisterDialog::registerUser (const QString & username, const QString & password)\fR [signal]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for VEDA-Qt-BANK from the source code\&.
