.TH "Transaction" 3 "VEDA-Qt-BANK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Transaction
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <bankmodel\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTransaction\fP (const QString &d, const QString &t, qint64 a, const QString &desc)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "QString \fBdate\fP"
.br
.ti -1c
.RI "QString \fBtype\fP"
.br
.ti -1c
.RI "qint64 \fBamount\fP"
.br
.ti -1c
.RI "QString \fBdescription\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Transaction::Transaction (const QString & d, const QString & t, qint64 a, const QString & desc)\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "qint64 Transaction::amount"

.SS "QString Transaction::date"

.SS "QString Transaction::description"

.SS "QString Transaction::type"


.SH "Author"
.PP 
Generated automatically by Doxygen for VEDA-Qt-BANK from the source code\&.
